import { Invoice, PurchaseOrder, GoodsReceivedNote, BankTransaction, JournalEntry, GLAccount, STPConfig } from '../types';

export const CHART_OF_ACCOUNTS: GLAccount[] = [
  { code: '1010', name: 'Operating Cash - Chase Main', category: 'Asset', subType: 'Cash & Cash Equivalents' },
  { code: '1020', name: 'Payroll Clearing Account', category: 'Asset', subType: 'Cash & Cash Equivalents' },
  { code: '1200', name: 'Accounts Receivable (Trade)', category: 'Asset', subType: 'Current Asset' },
  { code: '1300', name: 'Hardware & Finished Goods Inventory', category: 'Asset', subType: 'Inventory' },
  { code: '1410', name: 'Prepaid Expenses & Subscriptions', category: 'Asset', subType: 'Prepaid' },
  { code: '1450', name: 'Input Tax / VAT Receivable', category: 'Asset', subType: 'Tax Asset' },
  { code: '2000', name: 'Accounts Payable (Trade)', category: 'Liability', subType: 'Current Liability' },
  { code: '2050', name: 'Accrued Expenses & Purchases', category: 'Liability', subType: 'Current Liability' },
  { code: '2100', name: 'Sales Tax Payable', category: 'Liability', subType: 'Current Liability' },
  { code: '5100', name: 'Cloud & Hosting Infrastructure', category: 'Expense', subType: 'COGS / Tech' },
  { code: '5200', name: 'Freight, Inbound Logistics & Customs', category: 'Expense', subType: 'Operating Expense' },
  { code: '6000', name: 'Office Supplies & Computer Equipment', category: 'Expense', subType: 'Operating Expense' },
  { code: '6100', name: 'Legal, Tax & Consulting Fees', category: 'Expense', subType: 'Professional Services' },
  { code: '6200', name: 'Facility Management & Janitorial Services', category: 'Expense', subType: 'Facilities' },
  { code: '7100', name: 'Bank Service & Wire Fees', category: 'Expense', subType: 'Finance Expense' },
];

export const INITIAL_POS: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: 'PO-2025-8812',
    vendorName: 'Amazon Web Services, Inc.',
    issueDate: '2025-08-01',
    deliveryDate: '2025-08-31',
    currency: 'INR',
    subtotal: 14250.00,
    taxAmount: 1140.00,
    totalAmount: 15390.00,
    status: 'fulfilled',
    department: 'DevOps & Platform Engineering',
    costCenter: 'CC-402 (Infrastructure)',
    approver: 'Sarah Chen (VP Eng)',
    lineItems: [
      { id: 'pol-1', description: 'EC2 Compute Instances & Reserved Instances', quantity: 1, unitPrice: 8500.00, amount: 8500.00, glCode: '5100' },
      { id: 'pol-2', description: 'Amazon S3 Storage & Glacier Archive', quantity: 1, unitPrice: 3200.00, amount: 3200.00, glCode: '5100' },
      { id: 'pol-3', description: 'RDS Multi-AZ Aurora PostgreSQL Database Clusters', quantity: 1, unitPrice: 2550.00, amount: 2550.00, glCode: '5100' },
    ],
  },
  {
    id: 'po-2',
    poNumber: 'PO-2025-4420',
    vendorName: 'Apex Freight & Logistics Global',
    issueDate: '2025-08-10',
    deliveryDate: '2025-08-25',
    currency: 'INR',
    subtotal: 4200.00,
    taxAmount: 0.00,
    totalAmount: 4200.00,
    status: 'fulfilled',
    department: 'Supply Chain & Fulfillment',
    costCenter: 'CC-204 (Logistics)',
    approver: 'Marcus Brody (Director Ops)',
    lineItems: [
      { id: 'pol-4', description: 'Intermodal Freight Drayage - Long Beach to Dallas Hub', quantity: 2, unitPrice: 2100.00, amount: 4200.00, glCode: '5200' },
    ],
  },
  {
    id: 'po-3',
    poNumber: 'PO-2025-1109',
    vendorName: 'Nordic Hardware Systems Inc.',
    issueDate: '2025-08-15',
    deliveryDate: '2025-08-28',
    currency: 'INR',
    subtotal: 7600.00,
    taxAmount: 380.00,
    totalAmount: 7980.00,
    status: 'partially_received',
    department: 'IT Hardware & Infrastructure',
    costCenter: 'CC-101 (Corporate IT)',
    approver: 'Elena Rostova (CIO)',
    lineItems: [
      { id: 'pol-5', description: 'UltraSharp 32-inch 4K USB-C Hub Monitors (U3223QE)', quantity: 20, unitPrice: 380.00, amount: 7600.00, glCode: '1300' },
    ],
  },
  {
    id: 'po-4',
    poNumber: 'PO-2025-9921',
    vendorName: 'CleanPro Facility Management Ltd.',
    issueDate: '2025-08-01',
    deliveryDate: '2025-08-31',
    currency: 'INR',
    subtotal: 1450.00,
    taxAmount: 0.00,
    totalAmount: 1450.00,
    status: 'fulfilled',
    department: 'Real Estate & Workplace',
    costCenter: 'CC-501 (Workplace Operations)',
    approver: 'David Vance (Facilities Mgr)',
    lineItems: [
      { id: 'pol-6', description: 'Monthly Commercial HVAC & Janitorial Sanitization', quantity: 1, unitPrice: 1450.00, amount: 1450.00, glCode: '6200' },
    ],
  }
];

export const INITIAL_GRNS: GoodsReceivedNote[] = [
  {
    id: 'grn-1',
    grnNumber: 'GRN-2025-088',
    poNumber: 'PO-2025-8812',
    receivedDate: '2025-08-31',
    receivedBy: 'Automated Cloud Meter (API Sync)',
    warehouseLocation: 'Cloud Virtual Tenant (us-east-1)',
    items: [
      { lineItemId: 'pol-1', description: 'EC2 Compute Instances & Reserved Instances', quantityOrdered: 1, quantityReceived: 1, condition: 'accepted' },
      { lineItemId: 'pol-2', description: 'Amazon S3 Storage & Glacier Archive', quantityOrdered: 1, quantityReceived: 1, condition: 'accepted' },
      { lineItemId: 'pol-3', description: 'RDS Multi-AZ Aurora PostgreSQL Database Clusters', quantityOrdered: 1, quantityReceived: 1, condition: 'accepted' },
    ],
  },
  {
    id: 'grn-2',
    grnNumber: 'GRN-2025-090',
    poNumber: 'PO-2025-4420',
    receivedDate: '2025-08-26',
    receivedBy: 'Jorge Martinez',
    warehouseLocation: 'Dallas Central Depot - Dock 4',
    items: [
      { lineItemId: 'pol-4', description: 'Intermodal Freight Drayage - Long Beach to Dallas Hub', quantityOrdered: 2, quantityReceived: 2, condition: 'accepted' },
    ],
  },
  {
    id: 'grn-3',
    grnNumber: 'GRN-2025-091',
    poNumber: 'PO-2025-1109',
    receivedDate: '2025-08-29',
    receivedBy: 'Arthur Pendelton (Warehouse Receiving)',
    warehouseLocation: 'Austin Logistics Hub - Bay 2',
    items: [
      { lineItemId: 'pol-5', description: 'UltraSharp 32-inch 4K USB-C Hub Monitors (U3223QE)', quantityOrdered: 20, quantityReceived: 15, condition: 'shortage' },
    ],
    notes: 'Only 15 boxes delivered on bill of lading #BL-77182. Driver signed exception manifest stating 5 units held at distributor hub pending replenishment.',
  },
  {
    id: 'grn-4',
    grnNumber: 'GRN-2025-094',
    poNumber: 'PO-2025-9921',
    receivedDate: '2025-08-31',
    receivedBy: 'David Vance',
    warehouseLocation: 'HQ Building Floor 1-4',
    items: [
      { lineItemId: 'pol-6', description: 'Monthly Commercial HVAC & Janitorial Sanitization', quantityOrdered: 1, quantityReceived: 1, condition: 'accepted' },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-AWS-2025-9831',
    vendorName: 'Amazon Web Services, Inc.',
    vendorEmail: 'aws-invoicing@amazon.com',
    vendorTaxId: 'US-91-1646860',
    vendorAddress: '410 Terry Avenue North, Seattle, WA 98109',
    bankDetails: {
      bankName: 'JPMorgan Chase N.A.',
      routingNumber: '021000021',
      accountNumber: '••••••••4912',
      verified: true,
    },
    invoiceDate: '2025-08-31',
    dueDate: '2025-09-30',
    paymentTerms: 'Net 30',
    currency: 'INR',
    subtotal: 14250.00,
    taxRate: 0.08,
    taxAmount: 1140.00,
    totalAmount: 15390.00,
    poNumber: 'PO-2025-8812',
    extractionConfidence: 99.2,
    status: 'posted_to_gl',
    matchingStatus: 'exact_match',
    matchingConfidence: 100,
    sampleCategory: 'cloud_saas',
    anomalies: [],
    journalEntryId: 'je-1',
    notes: 'Straight-Through-Processed (STP): 100% matched against PO-2025-8812 and digital cloud delivery receipt. Auto-posted to GL account 5100.',
    lineItems: [
      {
        id: 'li-1',
        description: 'EC2 Compute Instances & Reserved Instances',
        quantity: 1,
        unitPrice: 8500.00,
        amount: 8500.00,
        glCode: '5100',
        glAccountName: 'Cloud & Hosting Infrastructure',
        costCenter: 'CC-402',
        confidence: 99.5,
      },
      {
        id: 'li-2',
        description: 'Amazon S3 Storage & Glacier Archive',
        quantity: 1,
        unitPrice: 3200.00,
        amount: 3200.00,
        glCode: '5100',
        glAccountName: 'Cloud & Hosting Infrastructure',
        costCenter: 'CC-402',
        confidence: 99.1,
      },
      {
        id: 'li-3',
        description: 'RDS Multi-AZ Aurora PostgreSQL Database Clusters',
        quantity: 1,
        unitPrice: 2550.00,
        amount: 2550.00,
        glCode: '5100',
        glAccountName: 'Cloud & Hosting Infrastructure',
        costCenter: 'CC-402',
        confidence: 99.0,
      },
    ],
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-AF-88291',
    vendorName: 'Apex Freight & Logistics Global',
    vendorEmail: 'billing@apexfreight.com',
    vendorTaxId: 'US-84-2918471',
    vendorAddress: '1040 Ocean Gateway Blvd, Long Beach, CA 90802',
    bankDetails: {
      bankName: 'Wells Fargo Commercial',
      routingNumber: '121000248',
      accountNumber: '••••••••7731',
      verified: true,
    },
    invoiceDate: '2025-08-27',
    dueDate: '2025-09-26',
    paymentTerms: 'Net 30',
    currency: 'INR',
    subtotal: 4284.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    totalAmount: 4284.00,
    poNumber: 'PO-2025-4420',
    extractionConfidence: 96.8,
    status: 'variance_flagged',
    matchingStatus: 'price_variance',
    matchingConfidence: 89.4,
    sampleCategory: 'logistics',
    anomalies: [
      {
        type: 'price_increase',
        title: 'Price Variance (+2.0%)',
        description: 'Invoice total (₹4,284.00) exceeds PO-2025-4420 (₹4,200.00) by ₹84.00 due to billed fuel index surcharge.',
        severity: 'low',
      }
    ],
    notes: 'Line item unit rate billed at ₹2,142 vs PO baseline of ₹2,100. Falls within the 2.5% logistics contractual fuel surcharge tolerance threshold.',
    lineItems: [
      {
        id: 'li-4',
        description: 'Intermodal Freight Drayage - Long Beach to Dallas Hub (incl. fuel surcharge)',
        quantity: 2,
        unitPrice: 2142.00,
        amount: 4284.00,
        glCode: '5200',
        glAccountName: 'Freight, Inbound Logistics & Customs',
        costCenter: 'CC-204',
        confidence: 96.8,
      },
    ],
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-NORDIC-7019',
    vendorName: 'Nordic Hardware Systems Inc.',
    vendorEmail: 'receivables@nordichw.com',
    vendorTaxId: 'US-47-9912048',
    vendorAddress: '880 Silicon Park Way, San Jose, CA 95134',
    bankDetails: {
      bankName: 'Silicon Valley Bank / First Citizens',
      routingNumber: '121140399',
      accountNumber: '••••••••1104',
      verified: true,
    },
    invoiceDate: '2025-08-29',
    dueDate: '2025-09-13',
    paymentTerms: '2/10 Net 30 (2% Early Pay Discount)',
    currency: 'INR',
    subtotal: 7600.00,
    taxRate: 0.05,
    taxAmount: 380.00,
    totalAmount: 7980.00,
    poNumber: 'PO-2025-1109',
    extractionConfidence: 98.4,
    status: 'variance_flagged',
    matchingStatus: 'quantity_variance',
    matchingConfidence: 74.0,
    sampleCategory: 'hardware',
    anomalies: [
      {
        type: 'qty_mismatch',
        title: 'Goods Receipt Shortage (3-Way Mismatch)',
        description: 'Invoice bills for 20 units (₹7,980.00), but warehouse GRN-2025-091 recorded receipt of only 15 units. Discrepancy of 5 units (₹1,995.00 with tax).',
        severity: 'high',
      },
    ],
    notes: 'Shortage detected: Payment block placed on ₹1,995.00 pending delivery of backordered 5 units or vendor credit memo.',
    lineItems: [
      {
        id: 'li-5',
        description: 'UltraSharp 32-inch 4K USB-C Hub Monitors (U3223QE)',
        quantity: 20,
        unitPrice: 380.00,
        amount: 7600.00,
        glCode: '1300',
        glAccountName: 'Hardware & Finished Goods Inventory',
        costCenter: 'CC-101',
        confidence: 98.4,
      },
    ],
  },
  {
    id: 'inv-4',
    invoiceNumber: 'INV-VERTEX-4011',
    vendorName: 'Vertex Strategy Partners LLC',
    vendorEmail: 'accounting@vertexstrategy.io',
    vendorTaxId: 'US-26-8841029',
    vendorAddress: '350 5th Avenue, Suite 4400, New York, NY 10118',
    bankDetails: {
      bankName: 'Citibank N.A.',
      routingNumber: '021000089',
      accountNumber: '••••••••9023',
      verified: true,
    },
    invoiceDate: '2025-09-02',
    dueDate: '2025-10-02',
    paymentTerms: 'Net 30',
    currency: 'INR',
    subtotal: 12500.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    totalAmount: 12500.00,
    poNumber: '',
    extractionConfidence: 94.7,
    status: 'variance_flagged',
    matchingStatus: 'missing_po',
    matchingConfidence: 61.2,
    sampleCategory: 'consulting',
    anomalies: [
      {
        type: 'po_missing',
        title: 'Non-PO Invoice Detected',
        description: 'No purchase order reference found on document. AI automatically mapped GL code 6100 and routed to CFO for approval.',
        severity: 'medium',
      },
      {
        type: 'high_amount',
        title: 'High Value Threshold (₹12,500.00)',
        description: 'Services exceeding ₹10,000 without master service agreement PO require secondary executive authorization.',
        severity: 'medium',
      }
    ],
    notes: 'Legal and technical M&A advisory services for Q3 restructuring. Requires department head approval.',
    lineItems: [
      {
        id: 'li-6',
        description: 'Strategic IT Architecture & Due Diligence Advisory Retainer',
        quantity: 1,
        unitPrice: 12500.00,
        amount: 12500.00,
        glCode: '6100',
        glAccountName: 'Legal, Tax & Consulting Fees',
        costCenter: 'CC-900',
        confidence: 94.7,
      },
    ],
  },
  {
    id: 'inv-5',
    invoiceNumber: 'INV-CP-9921-AUG',
    vendorName: 'CleanPro Facility Management Ltd.',
    vendorEmail: 'accounts@cleanpro-facility.com',
    vendorTaxId: 'US-38-1928374',
    vendorAddress: '1200 Industrial Blvd, Austin, TX 78701',
    bankDetails: {
      bankName: 'Bank of America N.A.',
      routingNumber: '111000025',
      accountNumber: '••••••••6642',
      verified: true,
    },
    invoiceDate: '2025-08-31',
    dueDate: '2025-09-15',
    paymentTerms: 'Net 15',
    currency: 'INR',
    subtotal: 1450.00,
    taxRate: 0.00,
    taxAmount: 0.00,
    totalAmount: 1450.00,
    poNumber: 'PO-2025-9921',
    extractionConfidence: 98.9,
    status: 'approved',
    matchingStatus: 'exact_match',
    matchingConfidence: 99.5,
    sampleCategory: 'facilities',
    anomalies: [],
    notes: 'Approved for disbursement. Bank statement clearing feed detected with exact match of ₹1,450.00.',
    lineItems: [
      {
        id: 'li-7',
        description: 'Monthly Commercial HVAC & Janitorial Sanitization',
        quantity: 1,
        unitPrice: 1450.00,
        amount: 1450.00,
        glCode: '6200',
        glAccountName: 'Facility Management & Janitorial Services',
        costCenter: 'CC-501',
        confidence: 98.9,
      },
    ],
  },
];

export const INITIAL_BANK_TRANSACTIONS: BankTransaction[] = [
  {
    id: 'tx-1',
    date: '2025-09-03',
    description: 'ACH DEBIT CLEANPRO FACILITY MGMT REF# INV-CP-9921',
    referenceNumber: 'ACH-88910248',
    amount: -1450.00,
    accountName: 'Chase Main Operating (...4012)',
    status: 'matched',
    matchedInvoiceId: 'inv-5',
    matchedInvoiceNumber: 'INV-CP-9921-AUG',
    matchedVendor: 'CleanPro Facility Management Ltd.',
    matchScore: 99.8,
    varianceAmount: 0.00,
  },
  {
    id: 'tx-2',
    date: '2025-09-01',
    description: 'WIRE OUT AMAZON WEB SERVICES US911646860',
    referenceNumber: 'WIR-2025-7719',
    amount: -15390.00,
    accountName: 'Chase Main Operating (...4012)',
    status: 'reconciled',
    matchedInvoiceId: 'inv-1',
    matchedInvoiceNumber: 'INV-AWS-2025-9831',
    matchedVendor: 'Amazon Web Services, Inc.',
    matchScore: 100,
    varianceAmount: 0.00,
    reconciledAt: '2025-09-01T14:22:00Z',
  },
  {
    id: 'tx-3',
    date: '2025-09-04',
    description: 'ACH DEBIT APEX FREIGHT GBL DRAYAGE',
    referenceNumber: 'ACH-99410214',
    amount: -4284.00,
    accountName: 'Chase Main Operating (...4012)',
    status: 'unreconciled',
    matchedInvoiceId: 'inv-2',
    matchedInvoiceNumber: 'INV-AF-88291',
    matchedVendor: 'Apex Freight & Logistics Global',
    matchScore: 94.2,
    varianceAmount: 0.00,
  },
  {
    id: 'tx-4',
    date: '2025-09-05',
    description: 'CHECK #40192 UNIDENTIFIED PAYEE',
    referenceNumber: 'CHK-40192',
    amount: -750.00,
    accountName: 'Chase Main Operating (...4012)',
    status: 'unreconciled',
    matchScore: 22.0,
  },
  {
    id: 'tx-5',
    date: '2025-09-05',
    description: 'CUSTOMER WIRE INFLOW - ACME CORP Q3 LICENSE',
    referenceNumber: 'WIR-882194',
    amount: 48500.00,
    accountName: 'Chase Main Operating (...4012)',
    status: 'unreconciled',
  }
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'je-1',
    entryNumber: 'JE-2025-0081',
    date: '2025-08-31',
    invoiceId: 'inv-1',
    invoiceNumber: 'INV-AWS-2025-9831',
    vendorName: 'Amazon Web Services, Inc.',
    status: 'posted',
    postedAt: '2025-08-31T23:59:12Z',
    postedBy: 'AI Autopilot Agent (STP Engine v4.2)',
    erpReference: 'NETSUITE-SYNC-982104',
    notes: 'Straight-Through-Processed 3-way match. Balanced entry verified.',
    totalDebit: 15390.00,
    totalCredit: 15390.00,
    isBalanced: true,
    lines: [
      {
        id: 'jl-1',
        accountCode: '5100',
        accountName: 'Cloud & Hosting Infrastructure',
        debit: 14250.00,
        credit: 0,
        description: 'AWS Cloud Services - EC2, S3, Aurora DB',
        costCenter: 'CC-402 (Platform Eng)',
      },
      {
        id: 'jl-2',
        accountCode: '1450',
        accountName: 'Input Tax / VAT Receivable',
        debit: 1140.00,
        credit: 0,
        description: 'State Sales Tax 8.0%',
        costCenter: 'Corporate',
      },
      {
        id: 'jl-3',
        accountCode: '2000',
        accountName: 'Accounts Payable (Trade)',
        debit: 0,
        credit: 15390.00,
        description: 'AP Liability - AWS Inc. due 2025-09-30',
        costCenter: 'Corporate AP',
      }
    ],
  }
];

export const DEFAULT_STP_CONFIG: STPConfig = {
  autoApproveConfidence: 92,
  priceVarianceTolerancePct: 2.5,
  autoPostToGL: true,
  duplicateHashCheck: true,
  strictThreeWayMatch: true,
  earlyPaymentDiscountAlert: true,
};
